include:
  - no-webapi.compose.yml
  - ingress.compose.yml

services:
  dialogporten-webapi:
    scale: 2
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.WebApi/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-redis:
        condition: service_healthy
      dialogporten-migrations:
        condition: service_completed_successfully
    environment:
      - Infrastructure:Redis:ConnectionString=dialogporten-redis:6379
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - Application:Dialogporten:BaseUri=http://dialogporten-webapi.localhost
      - Serilog__WriteTo__0__Name=Console
      - Serilog__MinimumLevel__Default=Debug
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dialogporten-webapi.rule=Host(`dialogporten-webapi.localhost`)"
      - "dave.url=https://dialogporten-webapi.localhost/swagger/index.html"
      - "dave.icon=openmoji:dotnet"
    volumes:
      - ./.aspnet/https:/https

  dialogporten-graphql:
    scale: 1
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.GraphQL/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-redis:
        condition: service_healthy
      dialogporten-migrations:
        condition: service_completed_successfully
    environment:
      - Infrastructure:Redis:ConnectionString=dialogporten-redis:6379
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - Application:Dialogporten:BaseUri=http://localhost:7214
      - Serilog__WriteTo__0__Name=Console
      - Serilog__MinimumLevel__Default=Debug
      - ASPNETCORE_ENVIRONMENT=Development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dalogporten-graphql.rule=Host(`dialogporten-graphql.localhost`)"
      - "dave.url=https://dialogporten-graphql.localhost/swagger/index.html"
      - "dave.icon=mdi:graphql"
    volumes:
      - ./.aspnet/https:/https
