services:
  dialogporten-postgres:
    image: postgres:16.3
    restart: always
    command: postgres -c wal_level=logical
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
      retries: 5

  dialogporten-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:8.17.4
    container_name: dialogporten-elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#    healthcheck:
#      test: curl --silent --fail http://localhost:9200 || exit 1
#      interval: 10s
#      retries: 5
#      start_period: 20s
#      timeout: 5s

  dialogporten-migrations:
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile
    environment:
      - Infrastructure__DialogDbConnectionString=${DB_CONNECTION_STRING}
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
    restart: "no"

  dialogporten-redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dialogporten-redisinsight:
    image: redis/redisinsight
    ports:
      - "7216:80"
    environment:
      RI_APP_PORT: 80
      RI_APP_HOST: '0.0.0.0'
    volumes:
      - redisinsight_cache:/data

volumes:
  redisinsight_cache:
    driver: local
