version: '3.9'

services:
  dialogporten-service:
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.Service/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-migrations:
        condition: service_completed_successfully
    environment:
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Development

  dialogporten-cdc:
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.ChangeDataCapture/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-migrations:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - ReplicationSlotName=outboxmessage_replication_slot
      - PublicationName=outboxmessage_publication
      - TableName=OutboxMessage
