version: '3'
services:
  postgres:
    image: postgres:15.4
    restart: always
    command: postgres -c wal_level=logical
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=Dialogporten
    ports:
    - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
    - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
    - "5672:5672"
    - "15672:15672"