include:
  - docker-compose-no-webapi.yml

services:
  dialogporten-webapi:
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.WebApi/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-redis:
        condition: service_healthy
    environment:
      - Infrastructure:Redis:ConnectionString=dialogporten-redis:6379
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - Serilog__WriteTo__0__Name=Console
      - Serilog__MinimumLevel__Default=Debug
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7214:8080"
    volumes:
      - ./.aspnet/https:/https
