include:
  - docker-compose-no-webapi.yml

services:
  dialogporten-webapi-ingress:
    image: nginx:1.25.4
    ports:
      - "7214:80"
    volumes:
      - ./nginx-webapi.conf:/etc/nginx/nginx.conf
    depends_on:
      - dialogporten-webapi
    restart: always

  dialogporten-webapi:
    scale: 2
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.WebApi/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-redis:
        condition: service_healthy
      dialogporten-migrations:
        condition: service_completed_successfully
    environment:
      - Infrastructure:Redis:ConnectionString=dialogporten-redis:6379
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - Application:Dialogporten:BaseUri=http://localhost:7214
      - Serilog__WriteTo__0__Name=Console
      - Serilog__MinimumLevel__Default=Debug
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./.aspnet/https:/https

  dialogporten-graphql-ingress:
    image: nginx:1.25.4
    ports:
      - "7215:80"
    volumes:
      - ./nginx-graphql.conf:/etc/nginx/nginx.conf
    depends_on:
      - dialogporten-graphql
    restart: always

  dialogporten-graphql:
    scale: 2
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.GraphQL/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-redis:
        condition: service_healthy
      dialogporten-migrations:
        condition: service_completed_successfully
    environment:
      - Infrastructure:Redis:ConnectionString=dialogporten-redis:6379
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - Application:Dialogporten:BaseUri=http://localhost:7214
      - Serilog__WriteTo__0__Name=Console
      - Serilog__MinimumLevel__Default=Debug
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./.aspnet/https:/https
