include:
  - docker-compose-no-webapi.yaml

services:
  dialogporten-webapi:
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.WebApi/Dockerfile
    restart: always
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
        
    environment:
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - Serilog__WriteTo__0__Name=Console
      - Serilog__MinimumLevel__Default=Debug
      - ASPNETCORE_URLS=https://+
      - ASPNETCORE_Environment=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webapi.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=supersecret
    ports:
      - "7214:443"
    volumes:
      - ./.aspnet/https:/https