version: '3'
services:
  postgres:
    image: postgres:14.7
    restart: always
    command: postgres -c wal_level=logical
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=Dialogporten
    ports:
    - "5432:5432"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
    - "10000:10000"
    - "10001:10001"
    - "10002:10002"
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
    - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
    - "5672:5672"
    - "15672:15672"