version: '3.9'
include:
  - docker-compose-db-redis.yml

services:
  dialogporten-sync-subject-resource-mappings-job:
    build:
      context: .
      dockerfile: src/Digdir.Domain.Dialogporten.Janitor/Dockerfile
    environment:
      - Infrastructure:DialogDbConnectionString=${DB_CONNECTION_STRING}
      - DOTNET_ENVIRONMENT=Development
    command: [ "sync-subject-resource-mappings" ]
    depends_on:
      dialogporten-postgres:
        condition: service_healthy
      dialogporten-migrations:
        condition: service_completed_successfully
