name: 'Azure Login with Bicep Upgrade'
description: 'Login to Azure and upgrade Bicep CLI'

inputs:
  client-id:
    description: 'Azure Client ID'
    required: true
  tenant-id:
    description: 'Azure Tenant ID'
    required: true
  subscription-id:
    description: 'Azure Subscription ID'
    required: false
  allow-no-subscriptions:
    description: 'Allow login without subscription ID'
    required: false
    default: 'false'

env:
  AZ_CLI_VERSION: 2.71.0

runs:
  using: "composite"
  steps:
    - name: OIDC Login to Azure Public Cloud
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # v2.2.0
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.allow-no-subscriptions == 'true' && '' || inputs.subscription-id }}
        allow-no-subscriptions: ${{ inputs.allow-no-subscriptions }}

    - name: Upgrade Azure Bicep
      shell: bash
      run: az bicep upgrade
