name: BuildTestPublish

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build-test-publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.x"

            - name: Restore
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Test
              run: dotnet test --no-build --configuration Release
