apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-resource-policy-information-job
spec:
  schedule: "10 3 * * *"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reindex-dialogsearch-job
spec:
  jobTemplate:
    spec:
      activeDeadlineSeconds: 172800
