@HostAddress = http://localhost:5007
@dialogId = 019d3e45-9862-7356-ad35-63872cd650e4
@dialogToken = "DIALOG_TOKEN_HERE"

### Verify DialogToken

POST {{HostAddress}}/dialogTokenVerify/
Accept: application/json

{
   "token": {{dialogToken}}
}

### Get dialog by id
GET {{HostAddress}}/dialog/{{dialogId}}
Accept: application/json

### List dialogs
GET {{HostAddress}}/dialogs
Accept: application/json
