source
| where not((DependencyType == "postgresql" or Name == "postgresql") and DurationMs < 100)
| where DependencyType in (
    "postgresql",
    "Other"
    )
| extend _NewName = case(
    DependencyType == "Other"
    and AppRoleName != "dp-be-prod-cae.dp-be-prod-sync-rp" // Too high cardinality due to looping over resources
    and (Name == "GET" or Name == "POST" or Name == "PUT")
    and isnotempty(Properties["url.full"]),
    strcat(Name, " ", extract(@"https?://[^/]+([^?]*)", 1, tostring(Properties["url.full"]))),
    Name
    )
| project-away Name
| extend Name = _NewName
| project-away _NewName
