name: Deploy apps

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_SOURCE_KEY_VAULT_NAME:
        required: true
      AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID:
        required: true
      AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP:
        required: true
      AZURE_ENVIRONMENT_KEY_VAULT_NAME:
        required: true
      AZURE_CONTAINER_APP_ENVIRONMENT_ID:
        required: true
      AZURE_APP_INSIGHTS_CONNECTION_STRING:
        required: true
      AZURE_APP_CONFIGURATION_NAME:
        required: true

    inputs:
      region:
        required: true
        type: string
      environment:
        required: true
        type: string
      dryRun:
        description: "If true, the deployment will be validated but not executed."
        required: false
        type: boolean
        default: false
      skipApproval:
        description: "If true, the deployment will skip approval."
        required: false
        type: boolean
        default: false
      skip:
        description: "If true, skip the deploy job."
        type: boolean
        default: false
concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  # if the dryrun input is true, we want to cancel any running deployments in order to not block the pipeline
  cancel-in-progress: ${{ inputs.dryRun }}
jobs:
  deploy:
    name: Deploy ${{ matrix.name }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: web-api-eu
          - name: web-api-so
    # todo: solve this in another way
    environment: "${{ !inputs.skipApproval && inputs.environment || 'test' }}"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy app ${{ matrix.name }}(${{ inputs.environment }})
        uses: azure/arm-deploy@v1
        id: deploy
        env:
          # parameters
          GIT_SHA: ${{ github.sha }}
          IMAGE_TAG: ${{ github.sha }}
          CONTAINER_APP_ENVIRONMENT_ID: ${{ secrets.AZURE_CONTAINER_APP_ENVIRONMENT_ID }}
          APP_INSIGHTS_CONNECTION_STRING: ${{ secrets.AZURE_APP_INSIGHTS_CONNECTION_STRING }}
          APP_CONFIGURATION_NAME: ${{ secrets.AZURE_APP_CONFIGURATION_NAME }}
          # secrets
          SOURCE_KEY_VAULT_SUBSCRIPTION_ID: ${{ secrets.AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID }}
          SOURCE_KEY_VAULT_RESOURCE_GROUP: ${{ secrets.AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP }}
          SOURCE_KEY_VAULT_NAME: ${{ secrets.AZURE_SOURCE_KEY_VAULT_NAME }}
          ENVIRONMENT_KEY_VAULT_NAME: ${{ secrets.AZURE_ENVIRONMENT_KEY_VAULT_NAME }}
        with:
          scope: subscription
          template: ./.azure/applications/${{ matrix.name }}/main.bicep
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          deploymentMode: Incremental
          deploymentName: dp-be-${{ inputs.environment }}-${{ matrix.name }}-${{ github.sha }}
          region: ${{ inputs.region }}
          failOnStdErr: true
          additionalArguments: "${{inputs.dryRun && '--what-if'}}"
          parameters: ./.azure/applications/${{ matrix.name }}/${{ inputs.environment }}.bicep

      # todo: move this out of this file
      - name: Start migration job
        uses: azure/CLI@v1
        if: ${{!inputs.dryRun}}
        with:
          azcliversion: 2.56.0
          inlineScript: |
            az containerapp job start -n ${{ steps.deploy.outputs.migrationJobName }} -g ${{ steps.deploy.outputs.resourceGroupName }}

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout
