name: Publish Schema to NPM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
env:
  WORKING_DIRECTORY: docs/schema/V1

permissions:
  id-token: write

jobs:
  publish-schema-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Update package version
        run: |
          jq '.version = "${{ inputs.version }}"' package.json > temp.json
          mv temp.json package.json
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run tests
        run: npm run test
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run build
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
