name: Deploy DotNet project to Azure Function App

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

    inputs:
      function-app-name:
        type: string
        required: true
      function-project-path:
        type: string
        required: true
      environment:
        type: string
        required: true
      skip:
        description: "If true, skip the deployment."
        type: boolean
        default: false

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy:
    name: Build and deploy ${{ inputs.function-app-name }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip }}
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: bash
        run: |
          pushd './${{ inputs.function-project-path }}'
          dotnet build -c Release -o ./output
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.function-app-name }}
          package: "${{ inputs.function-project-path }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
