name: Delete temporary GitHub deployments

on:
  workflow_call:
    inputs:
      gitSha: // Set git sha here? Or use the `${{ github.event.pull_request.head.sha }}` on line 19?
        required: true
        type: string

jobs:
  delete_github_deployments:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
    - name: Delete Previous deployments
      uses: actions/github-script@v6
      env:
        GITHUB_SHA_HEAD: ${{ github.event.pull_request.head.sha }}
      with:
        script: |
          const { GITHUB_SHA_HEAD } = process.env
          const deployments = await github.rest.repos.listDeployments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: GITHUB_SHA_HEAD
          });
          await Promise.all(
            deployments.data.map(async (deployment) => {
              // might not need to set this? They all seem to be inactive in the PR GUI 
              await github.rest.repos.createDeploymentStatus({ 
                owner: context.repo.owner, 
                repo: context.repo.repo, 
                deployment_id: deployment.id, 
                state: 'inactive' 
              });
              return github.rest.repos.deleteDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deployment.id
              });
            })
          );
