name: MigrationTesting

on:
  workflow_dispatch:
  push:
    branches: [ feature/AddCleanArchitectureLayout ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Generate EF migration script
        if: ${{inputs.publishArtifacts}}
        run: | 
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef migrations script --configuration Release --idempotent --startup-project src/Digdir.Domain.Dialogporten.Infrastructure --output ${{env.DOTNET_ROOT}}/artifacts/database/migrate.sql

      - name: Login to azure
        id: azureLogin
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get postgre connectionstring
        id: postgreConnectionString
        shell: pwsh
        run: >
          .azure/powershell/fetchKeyvaultSecret.ps1
          -secretId https://dppoc-kv-mdefv7a5ajvty.vault.azure.net/secrets/dialogportenPsqlConnectionString/80cac35665e74b3896f1ed9d758edd4d #${{ steps.bicep.outputs.psqlConnectionStringSecretUri }}

      - name: Apply EF migration script
        run: ${{ steps.postgreConnectionString.outputs.value }} -f ${{env.DOTNET_ROOT}}/artifacts/database/migrate.sql -q

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout