name: BuildTest

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.x"

            - name: Restore
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Test
              run: dotnet test --no-build --configuration Release

            - name: Upload azure bicep artifacts for IaC deployment
              if: ${{inputs.publishArtifacts}}
              uses: actions/upload-artifact@v4
              with:
                  name: azure-artifacts
                  path: .azure
