name: Build infrastructure

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  build:
    name: Build infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud with AzPowershell
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Lint Bicep files
        run: az bicep build --file .azure/main.bicep

      # todo: run deployment with Validate deployment mode to send a preflight request to Azure Resource Manager

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout
