name: "Check for changes"

on:
  workflow_call:
    outputs:
      azure:
        description: "Azure related files changed"
        value: ${{ jobs.check-for-changes.outputs.azure }}
      backend:
        description: "Backend related files changed"
        value: ${{ jobs.check-for-changes.outputs.backend }}

jobs:
  check-for-changes:
    name: Filter
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.paths-filter.outputs.backend == 'true' }}
      azure: ${{ steps.paths-filter.outputs.azure == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: paths-filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend:
              - 'src/**/*'
            azure:
              - '.azure/**/*'
            # todo: add additional files that should trigger a build
