# Deploys the created release to yt01
name: Test K6 performance for CI/CD
run-name: Test K6 performance for CI/CD 
on:
  push:
    branches:
      - 'performance/**'

jobs:

  run-performance-tests:
    name: "Run K6 performance tests"
    # we want the performance tests to be dependent on deployment of infrastructure and apps, but if infrastructure is skipped, we still want to run the tests
    uses: ./.github/workflows/workflow-run-k6-performance.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    strategy:
      max-parallel: 4
      matrix:
        files:
          - tests/k6/tests/serviceowner/performance/serviceOwnerSearchWithThresholds.js
          - tests/k6/tests/serviceowner/performance/createDialogWithThresholds.js
          - tests/k6/tests/serviceowner/performance/createTransmissionsWithThresholds.js
          - tests/k6/tests/enduser/performance/enduserSearchWithThresholds.js
      fail-fast: false
    with:
      environment: yt01
      apiVersion: v1
      vus: 1
      duration: 30s
      testSuitePath: ${{ matrix.files }}
      parallelism: 1
      breakpoint: false
      abortOnFail: false
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
