name: Workflow

on:
  workflow_dispatch:
  push:
    branches: [chore/restructure-bicep-and-actions]
    paths-ignore:
      - "tests/k6/**"

jobs:
  check-for-changes:
    name: Check for changes
    uses: ./.github/workflows/action-check-for-changes.yml

  build-and-test:
    name: Build and test backend
    uses: ./.github/workflows/action-build-and-test.yml
    needs: [check-for-changes]
    with:
      skip: ${{ needs.check-for-changes.outputs.hasBackendChanges != 'true' }}

  publish:
    name: Build and publish docker images
    uses: ./.github/workflows/action-publish.yml
    needs: [check-for-changes, build-and-test]
    secrets:
      GCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      skip: ${{ needs.check-for-changes.outputs.hasBackendChanges != 'true' }}
      dockerImageBaseName: ghcr.io/digdir/dialogporten-

  deploy-test:
    name: Deploy to test
    needs: [check-for-changes, publish]
    uses: ./.github/workflows/action-deploy.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SOURCE_KEY_VAULT_NAME: ${{ secrets.AZURE_SOURCE_KEY_VAULT_NAME }}
      AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID: ${{ secrets.AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID }}
      AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP: ${{ secrets.AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP }}
      APIM_DIGDIR_EMAIL: ${{ secrets.APIM_DIGDIR_EMAIL }}
    with:
      skip: ${{ needs.check-for-changes.outputs.hasAzureChanges != 'true' }}
      environment: test
      region: norwayeast
      dryRun: true

  deploy-slack-notifier-test:
    name: Deploy slack notifier (test)
    needs: [check-for-changes, deploy-test]
    uses: ./.github/workflows/action-deploy-function.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      skip: ${{ needs.check-for-changes.outputs.hasSlackNotifierChanges != 'true' }}
      function-app-name: "dp-be-test-slacknotifier-fa"
      function-project-path: "./src/Digdir.Tool.Dialogporten.SlackNotifier"
      environment: test

  dry-run-deploy-staging:
    name: Deploy to staging (dry run)
    needs: [check-for-changes, deploy-test]
    uses: ./.github/workflows/action-deploy.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SOURCE_KEY_VAULT_NAME: ${{ secrets.AZURE_SOURCE_KEY_VAULT_NAME }}
      AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID: ${{ secrets.AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID }}
      AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP: ${{ secrets.AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP }}
      APIM_DIGDIR_EMAIL: ${{ secrets.APIM_DIGDIR_EMAIL }}
    with:
      skip: ${{ needs.check-for-changes.outputs.hasAzureChanges != 'true' }}
      environment: staging
      region: norwayeast
      skipApproval: true
      dryRun: true

  deploy-staging:
    name: Deploy to staging
    needs: [check-for-changes, dry-run-deploy-staging]
    uses: ./.github/workflows/action-deploy.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SOURCE_KEY_VAULT_NAME: ${{ secrets.AZURE_SOURCE_KEY_VAULT_NAME }}
      AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID: ${{ secrets.AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID }}
      AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP: ${{ secrets.AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP }}
      APIM_DIGDIR_EMAIL: ${{ secrets.APIM_DIGDIR_EMAIL }}
    with:
      skip: ${{ needs.check-for-changes.outputs.hasAzureChanges != 'true' }}
      environment: staging
      region: norwayeast
      dryRun: true
