name: CI/CD YT01

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:


  run-performance-ci-cd:
    name: "Run K6 performance tests"
    # we want the performance tests to be dependent on deployment of infrastructure and apps, but if infrastructure is skipped, we still want to run the tests
    
    #needs: [deploy-apps, check-for-changes]
    
    uses: ./.github/workflows/workflow-run-k6-performance.yml
    secrets:
      TOKEN_GENERATOR_USERNAME: ${{ secrets.TOKEN_GENERATOR_USERNAME }}
      TOKEN_GENERATOR_PASSWORD: ${{ secrets.TOKEN_GENERATOR_PASSWORD }}
      K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
    
    strategy:
      max-parallel: 1
      matrix:
        files: 
          - tests/k6/tests/serviceowner/serviceOwnerSearchWithThresholds.js
          - tests/k6/tests/serviceowner/createDialogWithThresholds.js
          - tests/k6/tests/enduser/enduserSearchWithThresholds.js
    with:
      environment: yt01
      apiVersion: v1
      vus: 2
      duration: 1m
      tokens: both
      numberOfTokens: 100
      testSuitePath: ${{ matrix.files }}
    permissions:
      checks: write
      pull-requests: write
