name: CI/CD Pull Request Release Please

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "tests/k6/**"

jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    name: Send GitHub slack message
    steps:
    - name: Send GitHub slack message
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        channel-id: 'C07A822MM7T'
        payload-file-path: ".github/new-release-ready.json"