name: Deploy

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_SOURCE_KEY_VAULT_NAME:
        required: true
      AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID:
        required: true
      AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP:
        required: true
      APIM_DIGDIR_EMAIL:
        required: true

    inputs:
      region:
        required: true
        type: string
      environment:
        required: true
        type: string
      dryRun:
        description: "If true, the deployment will be validated but not executed."
        required: false
        type: boolean
        default: false
concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch secret keys from Azure Vault
        uses: azure/CLI@v1
        id: keyvault-keys
        with:
          azcliversion: 2.56.0
          inlineScript: |
            KEY_VAULT_KEYS=$(az keyvault secret list --vault-name ${{ secrets.AZURE_SOURCE_KEY_VAULT_NAME }} --subscription ${{ secrets.AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID }} --query "[].name" -o json)
            echo "::set-output name=key-vault-keys::$KEY_VAULT_KEYS"

      - name: Generate postgresql password
        id: pwd-generator
        shell: pwsh
        run: |
          Import-module "./.github/tools/pwdGenerator.ps1" -Force
          $password = (GeneratePassword -length 30).Password
          echo "::add-mask::$password"
          echo "::set-output name=postgresqlPassword::$password"

      - name: Deploy infrastructure (${{ inputs.environment }})
        uses: azure/arm-deploy@v1
        id: deploy
        env:
          # parameters
          GIT_SHA: ${{ github.sha }}
          KEY_VAULT_SOURCE_KEYS: ${{steps.keyvault-keys.outputs.key-vault-keys}}
          # secrets
          PG_ADMIN_PASSWORD: ${{ steps.pwd-generator.outputs.postgresqlPassword }}
          APIM_DIGDIR_EMAIL: ${{ secrets.APIM_DIGDIR_EMAIL }}
          SOURCE_KEYVAULT_SUBSCRIPTION_ID: ${{ secrets.AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID }}
          SOURCE_KEYVAULT_RESOURCE_GROUP: ${{ secrets.AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP }}
          SOURCE_KEYVAULT_NAME: ${{ secrets.AZURE_SOURCE_KEY_VAULT_NAME }}
        with:
          scope: subscription
          template: ./.azure/main.bicep
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          deploymentMode: Incremental
          deploymentName: dp-be-${{ inputs.environment }}-deployment-${{ github.sha }}
          region: ${{ inputs.region }}
          failOnStdErr: true
          additionalArguments: "${{inputs.dryRun && '--what-if'}}"
          parameters: ./.azure/.${{ inputs.environment }}.bicepparam

      - name: Start migration job
        uses: azure/CLI@v1
        if: ${{!inputs.dryRun}}
        with:
          azcliversion: 2.56.0
          inlineScript: |
            az containerapp job start -n ${{ steps.deploy.outputs.migrationJobName }} -g ${{ steps.deploy.outputs.resourceGroup }}

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout
