name: Deploy

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_SOURCE_KEY_VAULT_NAME:
        required: true
      AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID:
        required: true
      AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP:
        required: true
      APIM_DIGDIR_EMAIL:
        required: true

    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download bicep artifacts
        uses: actions/download-artifact@v4
        with:
          name: azure-artifacts
          path: .azure

      - name: OIDC Login to Azure Public Cloud with AzPowershell
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy infrastructure
        id: bicep
        shell: pwsh
        run: >
          .azure/deployBicep.ps1
          -gitSha ${{github.sha}} 
          -environment ${{ inputs.environment }}
          -subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          -sourceKeyVaultName ${{ secrets.AZURE_SOURCE_KEY_VAULT_NAME }}
          -sourceKeyVaultSubscriptionId ${{ secrets.AZURE_SOURCE_KEY_VAULT_SUBSCRIPTION_ID }}
          -sourceKeyVaultResourceGroup ${{ secrets.AZURE_SOURCE_KEY_VAULT_RESOURCE_GROUP }}
          -apiManagementDigDirEmail ${{ secrets.APIM_DIGDIR_EMAIL}}

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout
