name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      AZURE_CREDENTIALS:
        required: true
      DIALOGPORTEN_PSQL_CONNECTIONSTRING:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Login to azure
        id: azureLogin
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure
        run: >
          az deployment sub create
          --name dialogportenDeployment
          --location norwayeast
          --template-file .azure/main.bicep
          --parameters @.azure/main.parameters.json
          --parameters @.azure/main.parameters.${{inputs.environment}}.json
          --subscription 'Visual Studio Enterprise BDL'

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: 052982ed-1e94-4e26-bfd4-a65252931325
          resourceGroupName: DummyTextHere 
          template: .azure/main.bicep
          parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
          failOnStdErr: false

      - name: Fetch runners public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Open postgre firewall for migrations
        run: >
          az postgres flexible-server firewall-rule create 
          --rule-name GithubActions 
          --name dialogportenpgprod 
          --resource-group dialogporten-poc-rg 
          --start-ip-address ${{ steps.ip.outputs.ipv4 }}

      - name: Apply EF migration script
        run: ${{ secrets.DIALOGPORTEN_PSQL_CONNECTIONSTRING }} -f ./database/migrate.sql -q

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dialogporten-poc'
          slot-name: 'production'
          package: ./webApi

      - name: Close postgre firewall
        if: ${{failure() || success()}}
        continue-on-error: true
        run: >
          az postgres flexible-server firewall-rule delete 
          --rule-name GithubActions 
          --name dialogportenpgprod 
          --resource-group dialogporten-poc-rg
          --yes

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout