name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      #subscriptionId:
      #  required: true
      #  type: string
    secrets: 
      AZURE_CREDENTIALS:
        required: true
      DIALOGPORTEN_PSQL_CONNECTIONSTRING:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Login to azure
        id: azureLogin
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure
        shell: pwsh
        run: >
          .azure/deployBicep.ps1 
          -environment ${{ inputs.environment }}
          -subscriptionId ${{ vars.subscriptionId }}

      - name: Fetch runners public IP
        id: ip
        uses: haythem/public-ip@v1.3

      # This needs to target correct db
      - name: Open postgre firewall for migrations
        run: >
          az postgres flexible-server firewall-rule create 
          --rule-name GithubActions 
          --name dialogportenpgprod 
          --resource-group dialogporten-poc-rg 
          --start-ip-address ${{ steps.ip.outputs.ipv4 }}

      # This needs to target correct connection string
      - name: Apply EF migration script
        run: ${{ secrets.DIALOGPORTEN_PSQL_CONNECTIONSTRING }} -f ./database/migrate.sql -q

      # This needs to target correct web service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dialogporten-poc'
          slot-name: 'production'
          package: ./webApi

      # This needs to target correct db
      - name: Close postgre firewall
        if: ${{failure() || success()}}
        continue-on-error: true
        run: >
          az postgres flexible-server firewall-rule delete 
          --rule-name GithubActions 
          --name dialogportenpgprod 
          --resource-group dialogporten-poc-rg
          --yes

      - name: Logout from azure
        if: ${{failure() || success()}}
        continue-on-error: true
        run: az logout