name: Run k6 breakpoint test

on:
    push:
        branches:
            - 'performance/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: echo inputs
              run: echo "hello world"