# Manual dispatch workflow for testing deployment lag monitoring
name: Dispatch Deployment Lag Check
run-name: Dispatch Deployment Lag Check ${{ inputs.force_notification && '(Force Notify)' || '' }}

on:
  workflow_dispatch:
    inputs:
      days_threshold:
        description: "Days threshold for production lag warning"
        required: false
        type: number
        default: 3
      releases_threshold:
        description: "Release count threshold for staging/prod diff warning"
        required: false
        type: number
        default: 3
      force_notification:
        description: "Send notification regardless of thresholds"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  trigger-deployment-lag-monitor:
    name: Trigger Deployment Lag Monitor
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment lag monitor workflow
        run: |
          echo "Triggering deployment lag monitor with parameters:"
          echo "Days threshold: ${{ inputs.days_threshold }}"
          echo "Releases threshold: ${{ inputs.releases_threshold }}"
          echo "Force notification: ${{ inputs.force_notification }}"
          
          gh workflow run ci-cd-deployment-lag-monitor.yml \
            -f days_threshold=${{ inputs.days_threshold }} \
            -f releases_threshold=${{ inputs.releases_threshold }} \
            -f force_notification=${{ inputs.force_notification }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
