name: Show reindex dialogsearch progress

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to inspect"
        required: true
        type: choice
        options:
          - test
          - yt01
          - staging
          - prod

run-name: Reindex dialogsearch progress ${{ inputs.environment }}

concurrency:
  group: progress-reindex-dialogsearch-${{ inputs.environment }}

permissions:
  contents: read
  id-token: write

jobs:
  show-progress:
    name: Show progress (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      JOB_NAME: dp-be-${{ inputs.environment }}-reindex-search
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Azure Login
        uses: ./.github/actions/azure-login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show latest log lines
        shell: bash
        env:
          RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        run: |
          set -euo pipefail

          az extension add --name containerapp --allow-preview --upgrade -y

          execution_name="$(az containerapp job execution list \
            --name "${JOB_NAME}" \
            --resource-group "${RESOURCE_GROUP}" \
            --query "[?properties.status=='Running' || properties.status=='Processing'] | [0].name" \
            --output tsv || true)"

          if [[ -z "${execution_name}" ]]; then
            echo "No active execution found for ${JOB_NAME}"
            exit 1
          fi

          echo "Active execution: ${execution_name}"
          echo "Last 10 log lines:"

          if ! az containerapp job execution logs show \
            --name "${JOB_NAME}" \
            --resource-group "${RESOURCE_GROUP}" \
            --job-execution-name "${execution_name}"; then
            echo "Failed to retrieve logs for ${execution_name}"
            exit 1
          fi

      - name: Logout from Azure
        if: ${{ failure() || success() }}
        run: az logout
