name: Create/delete performance test

on:
  workflow_dispatch:
    inputs:
      apiVersion:
        description: 'API Version'
        required: true
        default: 'v1'
      environment:
        description: 'Environment (poc, test, staging)'
        required: true
        default: 'poc'

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run K6 tests
      uses: grafana/k6-action@v0.3.0
      with:
        filename: tests/k6/suites/createremove-perf-10-vus-1-min.js
      env:
        API_ENVIRONMENT: ${{ github.event.inputs.environment }}
        API_VERSION: ${{ github.event.inputs.apiVersion }}
        TOKEN_GENERATOR_USERNAME: ${{ secrets.TOKEN_GENERATOR_USERNAME }}
        TOKEN_GENERATOR_PASSWORD: ${{ secrets.TOKEN_GENERATOR_PASSWORD }}  
    
    - name: Store test summary
      uses: actions/upload-artifact@v3
      with:
        name: k6-summary-report
        path: summary.json

    - name: 'Publish test results'
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: 'junit.xml'
