name: PullRequest

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "tests/k6/**"

jobs:
  publish:
    uses: ./.github/workflows/BuildTestPublish.yml
    with:
      publishArtifacts: false
