name: PullRequest

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "tests/k6/**"

jobs:
  check-changes:
    uses: ./.github/workflows/CheckChanges.yml

  build:
    uses: ./.github/workflows/BuildAndTest.yml

  # todo: only if .azure-files are changed
  build-infrastructure:
    uses: ./.github/workflows/BuildInfrastructure.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      environment: "test"
