name: PullRequest

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "tests/k6/**"

jobs:
  check-for-changes:
    name: Check for changes
    uses: ./.github/workflows/CheckForChanges.yml

  build:
    uses: ./.github/workflows/BuildAndTest.yml
    needs: ["check-for-changes"]
    if: ${{ needs.check-for-changes.outputs.hasBackendChanges}}

  build-infrastructure:
    uses: ./.github/workflows/BuildInfrastructure.yml
    needs: ["check-for-changes"]
    if: ${{ needs.check-for-changes.outputs.hasAzureChanges}}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      environment: "test"
