name: "Get current version"
# might use previous tag as a version instead of the current version in file
# https://github.com/WyriHaximus/github-action-get-previous-tag
on:
  workflow_call:
    outputs:
      version:
        description: "Version"
        value: ${{ jobs.get-current-version.outputs.version }}

jobs:
  get-current-version:
    name: Filter
    permissions:
      contents: read
    runs-on: self-hosted
    outputs:
      version: ${{ steps.set-current-version.outputs.version }}
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Set current version
        id: set-current-version
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
