name: Workflow

on:
    workflow_dispatch:
    push:
        branches: [main]
        #paths: [ src/**, tests/**, .github/workflows/** ]
        paths-ignore:
            - "tests/k6/**"

jobs:
    buildTest:
        uses: ./.github/workflows/BuildTest.yml

    publish:
        needs: [buildTest]
        uses: ./.github/workflows/Publish.yml

    deployTest:
        needs: [publish]
        uses: ./.github/workflows/Deploy.yml
        secrets: inherit
        with:
            environment: test
