name: Run WebAPI E2E tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        description: "The branch or tag ref to run the tests on. Using default checkout ref if not provided."
        required: false
        default: ${{ github.ref }}
        type: string
    secrets:
      TOKEN_GENERATOR_USERNAME:
        required: true
      TOKEN_GENERATOR_PASSWORD:
        required: true

jobs:
  webapi-e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ inputs.ref }}

      - name: Set up .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: ./global.json

      - name: Run WebAPI E2E tests
        env:
          DOTNET_ENVIRONMENT: ${{ inputs.environment }}
          TokenGeneratorUser: ${{ secrets.TOKEN_GENERATOR_USERNAME }}
          TokenGeneratorPassword: ${{ secrets.TOKEN_GENERATOR_PASSWORD }}
        run: |
          dotnet test tests/Digdir.Domain.Dialogporten.WebAPI.E2E.Tests/Digdir.Domain.Dialogporten.WebAPI.E2E.Tests.csproj \
            --configuration Release \
            -- xUnit.Explicit=only
