name: Build syncroot OCI image

on:
  workflow_call:
    inputs:
      version:
        description: "Version tag for the syncroot OCI artifact"
        required: true
        type: string
      configTag:
        description: "App-config OCI tag to reference"
        required: true
        type: string
    secrets:
      GCR_PASSWORD:
        description: "Password for GitHub Container Registry"
        required: true

jobs:
  build-syncroot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCR_PASSWORD }}

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          curl -s https://fluxcd.io/install.sh | sudo bash

      - name: Render syncroot with app-config tag
        env:
          DIALOGPORTEN_CONFIG_TAG: ${{ inputs.configTag }}
        run: |
          tmp_dir=$(mktemp -d)
          cp -R flux/syncroot "${tmp_dir}/syncroot"
          export DIALOGPORTEN_CONFIG_TAG
          find "${tmp_dir}/syncroot" -type f -name '*.yaml' -print0 | xargs -0 -I{} sh -c 'envsubst < "$1" > "$1.tmp" && mv "$1.tmp" "$1"' _ {}
          flux push artifact oci://ghcr.io/altinn/dialogporten-syncroot:${{ inputs.version }} \
            --path="${tmp_dir}/syncroot" \
            --source="${{ github.server_url }}/${{ github.repository }}" \
            --revision="${{ github.sha }}"
