name: Workflow

on:
  workflow_dispatch:
  push:
    branches: [ feature/AddCleanArchitectureLayout ]
    #paths: [ src/**, tests/**, .github/workflows/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run bicep
        run: >
          .azure/deployBicep.ps1 
          -environment test
jobs:
  publish:
    uses: ./.github/workflows/BuildTestPublish.yml
    with:
      publishArtifacts: true

  deployPoc:
    needs: [ publish ]
    uses: ./.github/workflows/Deploy.yml
    secrets: inherit
    with:
      environment: poc

  #deployTest:
  #  needs: [ publish, deployPoc ]
  #  uses: ./.github/workflows/Deploy.yml
  #  secrets: inherit
  #  with:
  #    environment: test
    