# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - dialogporten-poc

on:
  push:
    branches: [ feature/AddCleanArchitectureLayout ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    #services:
    #  postgres:
    #    image: postgres
    #    ports:
    #      - 5432:5432
    #    env:
    #      POSTGRES_USER: postgres
    #      POSTGRES_PASSWORD: postgres
    #      POSTGRES_DB: testdb

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # TODO: Fix tests
      #- name: Test
      #  run: dotnet test --no-build --verbosity normal

      - name: Publish web api
        run: dotnet publish src/Digdir.Domain.Dialogporten.WebApi --no-build -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Generate EF migration script
        run: | 
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          #dotnet ef migrations script --idempotent --startup-project src/Digdir.Domain.Dialogporten.Infrastructure --output ${{env.DOTNET_ROOT}}/myapp/migrate.sql
          dotnet ef migrations bundle --no-build --startup-project src/Digdir.Domain.Dialogporten.Infrastructure --output ${{env.DOTNET_ROOT}}/myapp/efbundle.exe --configuration Release
          #dotnet ef migrations bundle --startup-project src/Digdir.Domain.Dialogporten.Infrastructure --output ${{env.DOTNET_ROOT}}/myapp/efbundle.exe --configuration Bundle

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    #environment:
    #  name: 'production'
    #  url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Fetch runners public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #- name: App Settings Variable Substitution
      #  uses: microsoft/variable-substitution@v1
      #  with:
      #    files: './appsettings.json'
      #  env:
      #    InfrastructureSettings.DialogueDbConnectionString: ${{ secrets.DIALOGPORTEN_ADO_CONNECTIONSTRING }}

      # TODO: This is not working due to the followin issue: https://github.com/Azure/postgresql/issues/33
      #- name: Apply EF migration script
      #  uses: azure/postgresql@v1
      #  with:
      #    connection-string: ${{ secrets.DIALOGPORTEN_PSQL_CONNECTIONSTRING }}
      #    server-name: dialogportenpgprod
      #    plsql-file: "./migrate.sql"
      #    arguments: "-q"

      - name: Open postgre firewall for migrations
        run: >
          az postgres flexible-server firewall-rule create 
          --rule-name FirewallRule1 
          --name dialogportenpgprod 
          --resource-group dialogporten-poc-rg 
          --start-ip-address ${{ steps.ip.outputs.ipv4 }}

      - name: Apply EF migration script
        run: ./efbundle.exe --connection "${{ secrets.DIALOGPORTEN_PSQL_CONNECTIONSTRING }}"

      - name: Close postgre firewall
        run: >
          az postgres flexible-server firewall-rule delete 
          --rule-name FirewallRule1 
          --name dialogportenpgprod 
          --resource-group dialogporten-poc-rg

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dialogporten-poc'
          slot-name: 'production'
          package: .

      - name: Update config
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'dialogporten-poc'
          slot-name: 'production'
          app-settings-json: |
              [
                  {
                      "name": "InfrastructureSettings:DialogueDbConnectionString",
                      "value": "${{ secrets.DIALOGPORTEN_ADO_CONNECTIONSTRING }}",
                      "slotSetting": true
                  }
              ]

      - name: Logout from azure
        #continue-on-error: true
        run: az logout