name: Run GraphQL E2E tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        description: "The branch or tag ref to run the tests on. Using default checkout ref if not provided."
        required: false
        default: ${{ github.ref }}
        type: string
    secrets:
      TOKEN_GENERATOR_USERNAME:
        required: true
      TOKEN_GENERATOR_PASSWORD:
        required: true

jobs:
  graphql-e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}

      - name: Set up .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          global-json-file: ./global.json

      - name: Run GraphQL E2E tests
        env:
          DOTNET_ENVIRONMENT: ${{ inputs.environment }}
          TokenGeneratorUser: ${{ secrets.TOKEN_GENERATOR_USERNAME }}
          TokenGeneratorPassword: ${{ secrets.TOKEN_GENERATOR_PASSWORD }}
        run: |
          dotnet test tests/Digdir.Domain.Dialogporten.GraphQl.E2E.Tests/Digdir.Domain.Dialogporten.GraphQl.E2E.Tests.csproj \
            --configuration Release \
            -- xUnit.Explicit=only
