name: Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    #paths: [ src/**, tests/**, .github/workflows/** ]
    paths-ignore:
      - 'tests/k6/**'

jobs:
  publish:
    uses: ./.github/workflows/BuildTestPublish.yml
    with:
      publishArtifacts: true

  deployPoc:
    needs: [ publish ]
    uses: ./.github/workflows/Deploy.yml
    secrets: inherit
    with:
      environment: poc
    