name: "Check for file changes"

on:
  workflow_call:
    inputs:
      infra_base_sha:
        description: "Base SHA for infrastructure changes"
        required: false
        default: ''
        type: string
      apps_base_sha:
        description: "Base SHA for application changes"
        required: false
        default: ''
        type: string
    outputs:
      hasInfraChanges:
        description: "Infrastructure related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasInfraChanges }}
      hasBackendChanges:
        description: "Backend related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasBackendChanges }}
      hasWebApiClientChanges:
        description: "WebApiClient related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasWebApiClientChanges }}
      hasTestChanges:
        description: "Test related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasTestChanges }}
      hasSwaggerSchemaChanges:
        description: "Swagger schema has changed"
        value: ${{ jobs.check-for-changes.outputs.hasSwaggerSchemaChanges }}
      hasGqlSchemaChanges:
        description: "GraphQL schema has changed"
        value: ${{ jobs.check-for-changes.outputs.hasGqlSchemaChanges }}
      hasMigrationChanges:
        description: "Migration related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasMigrationChanges }}
      hasSchemaPackageChanges:
        description: "Schema package content or infrastructure has changed"
        value: ${{ jobs.check-for-changes.outputs.hasSchemaPackageChanges }}

jobs:
  check-for-changes:
    name: Filter
    runs-on: ubuntu-latest
    outputs:
      hasInfraChanges: ${{ steps.filter.outputs.azure_any_modified == 'true' || steps.filter.outputs.github_workflows_any_modified == 'true' }}
      hasBackendChanges: ${{ steps.filter-backend.outputs.backend_any_modified == 'true' || steps.filter.outputs.github_workflows_any_modified == 'true' }}
      hasTestChanges: ${{ steps.filter-backend.outputs.tests_any_modified == 'true' }}
      hasSwaggerSchemaChanges: ${{ steps.filter-backend.outputs.swagger_schema_any_modified == 'true'}}
      hasGqlSchemaChanges: ${{ steps.filter-backend.outputs.gql_schema_any_modified == 'true'}}
      hasMigrationChanges: ${{ steps.filter-backend.outputs.migration_any_modified == 'true'}}
      hasWebApiClientChanges: ${{ steps.filter-backend.outputs.web_api_client_any_modified == 'true'}}
      hasSchemaPackageChanges: ${{ steps.filter-backend.outputs.schema_package_any_modified == 'true'}}
    steps:
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
        id: filter
        with:
          base_sha: ${{ inputs.infra_base_sha }}
          files_yaml: |
            azure:
              - '.azure/infrastructure/**/*'
              - '.azure/modules/**/*'
            github_workflows:
              - '.github/**/*'
              - '!.github/ISSUE_TEMPLATE/**/*'
              - '!.github/CODEOWNERS'
              - '!.github/pull_request_template.md'

      - name: Log infrastructure and workflow changes
        run: |
          echo "Infrastructure changes detected: ${{ steps.filter.outputs.azure_any_modified }}"
          echo "Github workflows changes detected: ${{ steps.filter.outputs.github_workflows_any_modified }}"
          echo "Changed infrastructure files:"
          echo "${{ steps.filter.outputs.azure_modified_files }}"
          echo "Changed github workflows files:"
          echo "${{ steps.filter.outputs.github_workflows_modified_files }}"

      - uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # v45.0.1
        id: filter-backend
        with:
          base_sha: ${{ inputs.apps_base_sha }}
          files_yaml: |
            backend:
              - 'src/**/*'
              - '.azure/applications/**/*'
              - '.azure/modules/containerApp/**/*'
            tests:
              - 'tests/**/*'
            web_api_client:
              - 'src/Digdir.Library.Dialogporten.WebApiClient/**/*'
            swagger_schema:
              - 'docs/schema/V1/swagger.verified.json'
            gql_schema:
              - 'docs/schema/V1/schema.verified.graphql'
            migration: 
              - 'src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/**/*'
            schema_package:
              - 'docs/schema/V*/**/*'

      - name: Log backend changes
        run: |
          echo "Backend changes detected: ${{ steps.filter-backend.outputs.backend_any_modified }}"
          echo "Test changes detected: ${{ steps.filter-backend.outputs.tests_any_modified }}"
          echo "Web API client changes detected: ${{ steps.filter-backend.outputs.web_api_client_any_modified }}"
          echo "Swagger schema changes detected: ${{ steps.filter-backend.outputs.swagger_schema_any_modified }}"
          echo "GraphQL schema changes detected: ${{ steps.filter-backend.outputs.gql_schema_any_modified }}"
          echo "Migration changes detected: ${{ steps.filter-backend.outputs.migration_any_modified }}"
          echo "Schema package changes detected: ${{ steps.filter-backend.outputs.schema_package_any_modified }}"
          echo "Changed backend files:"
          echo "${{ steps.filter-backend.outputs.backend_modified_files }}"
