name: Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main, mainTestBranch ]
    #paths: [ src/**, tests/**, .github/workflows/** ]

jobs:
  publish:
    uses: ./.github/workflows/BuildTestPublish.yml
    with:
      publishArtifacts: true

  deployPoc:
    needs: [ publish ]
    uses: ./.github/workflows/Deploy.yml
    secrets: inherit
    with:
      environment: ProofOfConsept

  #deployTest:
  #  needs: [ publish, deployPoc ]
  #  uses: ./.github/workflows/Deploy.yml
  #  secrets: inherit
  #  with:
  #    environment: Test
    