name: "Check for file changes"

on:
  workflow_call:
    inputs:
      base_sha:
        description: "Base SHA to compare changes against"
        required: false
        type: string
    outputs:
      hasAzureChanges:
        description: "Azure related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasAzureChanges }}
      hasBackendChanges:
        description: "Backend related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasBackendChanges }}
      hasTestChanges:
        description: "Test related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasTestChanges }}
      hasSlackNotifierChanges:
        description: "Slack Notifier function related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasSlackNotifierChanges }}
      hasSchemaChanges:
        description: "Schema has changed"
        value: ${{ jobs.check-for-changes.outputs.hasSchemaChanges }}
      hasMigrationChanges:
        description: "Migration related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasMigrationChanges }}

jobs:
  check-for-changes:
    name: Filter
    runs-on: ubuntu-latest
    outputs:
      hasBackendChanges: ${{ steps.filter.outputs.backend_any_modified == 'true' }}
      hasTestChanges: ${{ steps.filter.outputs.tests_any_modified == 'true' }}
      hasAzureChanges: ${{ steps.filter.outputs.azure_any_modified == 'true' }}
      hasSlackNotifierChanges: ${{ steps.filter.outputs.slackNotifier_any_modified == 'true'}}
      hasSchemaChanges: ${{ steps.filter.outputs.schema_any_modified == 'true'}}
      hasMigrationChanges: ${{ steps.filter.outputs.migration_any_modified == 'true'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@v45
        id: filter
        with:
          base_sha: ${{ inputs.base_sha }}
          files_yaml: |
            backend:
              - '.github/**/*'
              - 'src/**/*'
              - '.azure/applications/**/*'
              - '.azure/modules/containerApp/**/*'
            tests:
              - 'tests/**/*'
            azure:
              - '.github/**/*'
              - '.azure/infrastructure/**/*'
              - '.azure/modules/**/*'
            slackNotifier:
              - '.github/**/*'
              - 'src/Digdir.Tool.Dialogporten.SlackNotifier/**/*'
            schema:
              - 'docs/schema/V1/**/*'
            migration: 
              - 'src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/**/*'
